disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - toggle_bool
  - unavailable_function

excluded:
  - .build
  - DerivedData
  - JugglerTests
  - JugglerUITests

line_length:
  warning: 120
  error: 200

identifier_name:
  min_length: 1
  max_length: 50

type_name:
  min_length: 2
  max_length: 50
